# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mahmood Magic
email: magicmahmood@gmail.com
description: Mahmood Magic is a world class duo performing magic and mentalism in Toronto, Vaughan, and the GTA. The duo have performed at corporate events, showers, birthdays and other special events. Book an event today!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mahmoodmagic.com" # the base hostname & protocol for your site
gems:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
